### ISSUE TITLE
PKCS7_dataFinal failed using SafeNet eToken on Ubuntu 24.04

### ISSUE THREAD

**Issue by gwechsel** [mtrojnar/osslsigncode#468]
osslsigncode 2.10 sign fails on Ubuntu 24.04, OpenSSL 3.0.13, safenetauthenticationclient-core_10.9.4723_amd64.deb, and SafeNet eToken with the following error.

```
osslsigncode sign -provider /usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11.so -pkcs11module /usr/lib/libeTPkcs11.so -certs 'XYZ.pem' -key 'pkcs11:token=XYZ;type=private' -h sha256 -in XYZ.dll -out XYZ.dll.signed
Enter pass phrase for PKCS#11 Token (Slot 17 - SafeNet eToken 5100 [eToken 5110 SC] 00 00):
PKCS7_dataFinal failed
Failed to sign spcIndirectDataContent
Failed to set signed content
Unable to prepare new signature
8070E6899C710000:error:42000054:/usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11.so:p11prov_GetOperationState:reason(84):interface.gen.c:279:Error returned by C_GetOperationState
8070E6899C710000:error:42000054:/usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11.so:p11prov_SignFinal:reason(84):interface.gen.c:717:Error returned by C_SignFinal
Failed
```

Signing with the same token works fine on Ubuntu 20.04, OpenSSL 1.1.1f, safenetauthenticationclient-core_10.9.4723_amd64.deb, and SafeNet eToken. osslsigncode 1.7.1, using: 
OpenSSL 1.1.1f  31 Mar 2020
libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
libgsf 1.14.46

Any help would be highly appreciated.

**Comment by gwechsel** [comment]
Sorry, found the issue on our side,....
